name: deploy

on: push

jobs:
  build: 
    runs-on: ubuntu-latest

    steps:
      - name: Print variable
        run: echo "${{ secrets.MY_SECRET }}"

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test

      - name: Build
        run: npm run build

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public
      
      - name: Checkout
        uses: actions/checkout@v4

  deploy:
    needs: build
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: write
      pages: write
      deployments: write

    environment:
      name: github-pages
      url: ${{ steps.deployment-pages.outputs.page_url }}

    steps:
      - name: Deploy
        id: deployment-pages
        uses: actions/deploy-pages@v4

  notify:
    name: Notify
    runs-on: ubuntu-latest
    needs: deploy
    if: always()

    steps:
      - name: Notify
        uses: peter-evans/slack-github-action@v2
        with:
          status: ${{ job.status }}
          channel: '#general'
          text: 'Deployment completed with status: ${{ job.status }}'
          token: ${{ secrets.SLACK_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


